import Config

# Configure your database
config :cc_spending_api, CcSpendingApi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "cc_spending_api_dev",
  stacktrace: true,
  port: 5434,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :cc_spending_api, CcSpendingApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 8888],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IWfknKKOdYLyQOtX7mEzFyk8rCH822TRlv5UlzY5Id3O2tElcNBERqodTOSWA/D6",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:cc_spending_api, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:cc_spending_api, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :cc_spending_api, CcSpendingApiWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/cc_spending_api_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :cc_spending_api, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :cc_spending_api, CcSpendingApiWeb.Guardian,
  issuer: "cc_spending_api",
  secret_key: "op7kQT+LmtwO9FRQQIgRvG33puUDeLvm4xU9otpxR4w8/BpIHCeDRWGeOBN+57PF"

config :guardian, Guardian.DB,
  # Add your repository module
  repo: CcSpendingApi.Repo,
  # default
  schema_name: "guardian_tokens",
  # ttl: {1, :seconds},
  # store all token types if not set
  # token_types: ["refresh_token"],
  # default: 60 minutes
  sweep_interval: 60
